services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    
    environment:
      MYSQL_ROOT_PASSWORD: Dedeepya@02
      MYSQL_DATABASE: bookingdb
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here
    
    

  backend:
    image: 2300030813/docker-backend-gitactions:latest
    container_name: springboot
    ports:
      - "1700:1700"
    depends_on:
      - mysqldb
    restart: on-failure
    

  frontend:
    image: 2300030813/docker-frontend-gitactions:latest
    container_name: react
    ports:
      - "7001:80"
    depends_on:
      - backend
    restart: on-failure
    

    
# Declare volumes at the bottom
volumes:
  mysql-data:


